### Site Settings ###
title               : Maciej Kania
description         : >-
                      Under construction ... 
baseurl             : ""                          # Empty because you host at kaniamaciej.github.io directly
repository          : kaniamaciej/kaniamaciej.github.io
remote_theme        : yousinix/portfolYOU
open_new_tab        : true                         # Opens external URLs in a new tab


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                       # These paths are excluded from the navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
# The key names here (email, github, bluesky...) are matched against _data/social-media.yml
# to pick the right icon. Add or remove lines to show/hide social icons in the landing page.
author:
  name              : Maciej Kania
  image             : /images/hike_pic.jpg          
  email             : maciej.kania@ist.ac.at
  github            : kaniamaciej
  bluesky           : kaniamaciej.bsky.social      
# linkedin          : your_username
# twitter           : your_username
  googlescholar     : https://scholar.google.com/citations?hl=pl&user=7v4emWUAAAAJ 
# orcid             : 0009-0003-1653-0698 


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false


### Exclude from processing ###
exclude:
  - README.md
  - LICENSE
  - "*.log"
  - Gemfile
  - Gemfile.lock
